[package]
name = "bb-lib-http-listener"
version = "v1.0.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = "0.7.5"
hyper = { workspace = true }
hyper-util = { workspace = true, features = ["tokio"] }
pin-project-lite = { workspace = true }
tokio = { workspace = true, features = ["net", "signal", "rt-multi-thread"] }
tower = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
bb-lib-tracing = { path = "../bb-lib-tracing" }
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
