[package]
name = "bb-lib-event"
version = "1.2.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }
bb-lib-nats-streams = { path = "../bb-lib-nats-streams" }
bytes = "1.6.0"
opentelemetry = "0.24.0"
tracing.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
bb-lib-tracing = { path = "../bb-lib-tracing" }
bb-lib-metrics = { path = "../bb-lib-metrics" }
metrics = "0.23.0"
lazy_static.workspace = true
async_once = "0.2.6"
config = "0.14.0"

[dev-dependencies]
tokio = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = "0.24.0"
