[package]
name = "bb-lib-tracing"
version = "2.0.2"
edition = "2021"

# [[bin]]
# name = "metric_test"
# metric_test = "metric_test/main.rs"

[dependencies]
anyhow = { workspace = true }
# color-eyre = "0.6.2"
lazy_static = { workspace = true }
opentelemetry = { version = "0.24.0", features = ["logs", "metrics"] }
opentelemetry-appender-tracing = "0.5.0"
opentelemetry-otlp = { version = "0.17.0", features = ["metrics", "logs", "serde", "serialize", "tls", "http", "http-proto"] }
opentelemetry-semantic-conventions = "0.16.0"
opentelemetry-stdout = { version = "0.5.0", features = ["trace"] }
opentelemetry_sdk = { version = "0.24.0", features = ["rt-tokio", "rt-tokio-current-thread"] }
rand = { workspace = true }
# sentry = "0.32.2"
# sentry-tracing = "0.32.2"
tonic = { version = "0.12.0", default-features = false, features = ["tls", "transport"] }
tracing = { workspace = true }
tracing-appender = "0.2.3"
tracing-loki = "0.2.5"
tracing-opentelemetry = "0.25.0"
tracing-subscriber = { version = "0.3.18", features = ["registry", "chrono", "json", "serde", "serde_json", "tracing", "tracing-serde", "env-filter"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
url = "2.5.2"
