[package]
name = "bb-lib-metrics"
version = "v1.2.0"
edition = "2021"

[dependencies]
metrics = "0.23.0"
metrics-exporter-prometheus = { version = "0.15.1", default-features = false, features = ["http-listener", "push-gateway"] }
aws-lc-sys = { version = "0.19.0", features = ["bindgen", "ssl"] }
tokio = { workspace = true }
anyhow = { workspace = true }
hyper = { workspace = true }
tracing = { workspace = true }
