[package]
name = "bb-lib-nats-streams"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-nats = "0.35.0"
bincode = "1.3.3"
bytes = "1.6.0"
futures = { workspace = true }
bb-lib-http-listener = { path = "../bb-lib-http-listener", version = "0.1.0" }
petname = "2.0.2"
rand = { workspace = true }
serde = {  workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros", "signal", "sync"] }
tower = "0.4.13"
tracing = { workspace = true }
opentelemetry = "0.23.0"
tokio-util = "0.7.11"

[dev-dependencies]
bb-lib-tracing = { path = "../bb-lib-tracing", version = "0.1.0" }
reqwest = { version = "0.12.4", features = ["json"] }
