[package]
name = "simian-bin-cfg-creator"
version = "2.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
simian-config = { path = "../simian-config", features = ["autotask", "jira", "surreal", "swimlane", "dev"] }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true }
serde_json = { workspace = true }
