####################################################################################################
## Builder
####################################################################################################
FROM rust:1.78.0 AS builder
WORKDIR /app
COPY . .
RUN --mount=type=ssh cargo build --release --bin log_emitter

####################################################################################################
## Final images
####################################################################################################

####################################################################################################
# Log-Emitter
####################################################################################################
FROM ghcr.io/bluebastion/dev-bb-rs-builder:v0.1.0 as bb-lib-emitter
ARG RUST_BIN="log_emitter"
ENV RUST_BIN $RUST_BIN
ENV RUST_LOG "debug"
ENV CARGO_PKG_NAME "log-emitter"
ENV SERVICE_NAME "log-emitter"
ENV SERVICE_VERSION "0.1.0"
COPY --from=builder /app/target/release/$RUST_BIN /usr/local/bin/$RUST_BIN
# ENTRYPOINT [ "/bin/bash", "-c" ]
# CMD ["${RUST_BIN}"]
