[package]
name = "simian-llm"
version = "2.0.2"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { workspace = true }
chrono = { workspace = true }
metrics = { workspace = true }
simian-base-api = { path = "../simian-base-api" }
simian-nats-streams = { path = "../simian-nats-streams" }
simian-tracing = { path = "../simian-tracing" }
simian-metrics = { path = "../simian-metrics" }

[dev-dependencies]

[[bin]]
name = "llm-agent"
path = "src/bin/llm-agent.rs"
