[package]
name = "simian-llm"
version = "2.0.2"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
metrics = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
simian-base-api = { path = "../simian-base-api" }
simian-tracing = { path = "../simian-tracing" }
simian-metrics = { path = "../simian-metrics" }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
futures = { workspace = true }
simian-nats-streams = { path = "../simian-nats-streams" }
