[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.chek]
command = "cargo"
args = [
    "run",
    "-p", "cfg_creator",
    "--bin", "cfg_creator",
    "--", "surreal",
    "--uri", "ws://localhost:8000",
    "--ns", "root",
    "--db", "root",
    "--user", "root",
    "--pass", "root",
    "--auth-level", "root"
]

