[package]
name = "simian-event"
version = "2.0.2"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bincode = "1.3.3"
bytes = "1.6.0"
chrono = { workspace = true }
config = "0.14.0"
futures = "0.3"
lazy_static.workspace = true
async_once = "0.2.6"
metrics = "0.23.0"
opentelemetry = "0.24.0"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
simian-metrics = { path = "../simian-metrics" }
simian-nats-streams = { path = "../simian-nats-streams" }
simian-tracing = { path = "../simian-tracing" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "sync", "fs", "io-util"] }
tracing.workspace = true
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
tokio = { workspace = true }
tracing = { workspace = true, features = ["log"] }
tracing-opentelemetry = "0.24.0"
