[package]
name = "simian-metrics"
version = "2.0.2"
edition = "2021"

[dependencies]
metrics = "0.23.0"
metrics-exporter-prometheus = { version = "0.15.1", default-features = false, features = ["http-listener", "push-gateway"] }
# aws-lc-sys = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
hyper = { workspace = true }
tracing = { workspace = true }
