[package]
name = "simian-iggy-streams"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
simian-base-api = { path = "../simian-base-api" }
bytes = { workspace = true }
futures = { workspace = true }
iggy = "0.9.0"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tracing-subscriber = "0.3"
