[package]
name = "simian-viz-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = { version = "0.7.5", features = ["ws"] }
futures = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
simian-base-api = { path = "../simian-base-api" }
simian-nats-streams = { path = "../simian-nats-streams" }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = "0.1"
tower = { workspace = true }
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { workspace = true, features = ["v4", "serde"] }
